alias rm='rm -i'
alias R='R --no-save --no-restore --quiet'
alias vim='vim --servername VIM'
alias tvim='vim --servername VIM'
alias tree='tree --dirsfirst --charset ascii' 
alias mdv='~/dotfiles/terminal_markdown_viewer/mdv.py'
