alias rm='rm -i'
alias R='R --no-save --no-restore --quiet'
alias vim='vim --servername VIM'
alias tvim='vim --servername VIM'
alias tree='tree --dirsfirst' 
alias mdv='~/terminal_markdown_viewer/mdv.py'
